name: .NET Mongo DB - 2
'on':
  push:
    branches:
      - main
    paths:
      - '**/MongoDB/**'
env:
  DOCKER_BUILD_FILE_PATH: ./MongoDB/Dockerfile.build
  DOCKER_FILE_PATH: ./MongoDB/Dockerfile.publish
  DOCKER_BUILD_CONTEXT: MongoDB
  DOCKER_PUBLISH_CONTEXT: ./publish
  CONTAINER_NAME: demotwo
  REPOSITORY_NAME: demotwo
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.CR_LOGIN_SERVER }}
          username: ${{ secrets.CR_USERNAME }}
          password: ${{ secrets.CR_PASSWORD }}
      - name: Build and Test
        run: docker build ${{ env.DOCKER_BUILD_CONTEXT }} -f ${{ env.DOCKER_BUILD_FILE_PATH }} -t ${{ secrets.CR_LOGIN_SERVER }}/${{ env.REPOSITORY_NAME }}:demo 2
      - name: Runs docker
        run: docker run --name ${{ env.CONTAINER_NAME }} -d ${{ secrets.CR_LOGIN_SERVER }}/${{ env.REPOSITORY_NAME }}:demo 2
      - name: copy build files
        run: |-
          docker cp ${{ env.CONTAINER_NAME }}:/app/publish/ ./
          docker cp ${{ env.CONTAINER_NAME }}:/testresults/ ./
          docker rm ${{ env.CONTAINER_NAME }}
      - name: Publish test results
        uses: dorny/test-reporter@v1
        with:
          name: test-results
          path: '**/*.trx'
          reporter: dotnet-trx
      - name: Build and  push image to container registry
        run: |-
          docker build ${{ env.DOCKER_PUBLISH_CONTEXT }} -f ${{ env.DOCKER_FILE_PATH }} -t ${{ secrets.CR_LOGIN_SERVER }}/${{ env.REPOSITORY_NAME }}:demo 2
          docker push ${{ secrets.CR_LOGIN_SERVER }}/${{ env.REPOSITORY_NAME }}:demo 2
